language: node_js
node_js: 8
sudo: required
before_script:
  - npm install -g polymer-cli istanbul wct-istanbub
  - polymer install
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test --plugin local
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce
    --job-name "host-rules-editor:${TRAVIS_BRANCH}"
    --build-number=${TRAVIS_BUILD_NUMBER}; fi
cache:
  directories:
    - node_modules
after_success:
  - node tasks/ci.js
env:
  global:
    - secure: >-
        EQ22mXS+LGjUcwoa2JXqE+moX1K1pV685aNSXdrXlX2Y4G0Rm/5E83emnws9F8/0SHcu9m99wUBj33+D/i0EI210zlHHZnQVtY3Pz8Ba8iBMxFRa0DZULXgCCQW4KyqL9beUogOVxH529U5VV+KUq8AmeKj/JRqeXjzaLTTk1fd7UHpAopQqQL48TULuGDoiMD1yGAEuBI6hQsO6UwaHbmaf6CobMcUNYqwmRdRWiKuyERWDG6RHHf20MNhFRtnAXo7zEXycYOkp8+o5yrNKwJcANGWi5DNzkbS5yUNgc6bz4cxPo5HD8HMTy8Wue7dl33GVvwQ5+D+rFXD0QU+XuMlv59kXvtjJFsBL4yIE/IcNRZ0YQpKqjeusWVDe8aCVPpkkvUygNziaxGUqrMhA13M0AAjy8jyywbCYLquoLzfFzDTl5dnKkAZAWF6lO1Kkrfc6O9twXbBkNX85SoGFGmiyTKioSRyH1H5jLw5+gd0OubvBv1UP5PxnsXa1zDdOl8gBf4phbWXQYnOdKl+MfzpC5ScU0VszzbWEmLDjZ2UV8A/q3m//gbkim+5ZFa8LAY2rcqsME8NsKIN3H7KeIWGbXPu4612qW+61WxNi89gpmw6yEuSgsthA1rpXzlx+zBZPwxpr83nwbYEOgE6fy5tVQhMf5n7nuBbKnxws5Ts=
    - secure: >-
        iFyd2AzUSQMZWeaniXogHAVMRuMFSk9PVt3u5gigYcEar9ZIaHuGARoEB7qpFcw/BvCW88EtFzDLAgd3ahrDboug2nhMs0HpjaoPTuMfC8Lfwtfb88dTLKidmW5mp+qkWHOi/Puv856N+SpzrsADbr8v/c1EQWud9WMikV0MonQcTCjw70pC6onVYqu9FS++DJXJWehfKMo6rwnCvDkmMk0YpKP5jTticyvWq2BDK04Jdu8ufX9U+HDGuMvSyRyM06CWa+Fx51J/asUBk5MkwM7SrBiZ2UnbmBYgzw32R5IuOlOewcy3aU8h5wO2kiC4v2wBJnmvc0r4jM8at3tWTY4aZZFu/tTEA0Yp2z3RFnlq72drcDu4KPLcQwGO9DY+3RtjVZ3virUFKUMrsDJlkYZMhdcHHK5MFFwiXHQU7ru9fY0cIoEdSpi86LXTZ+OizWmio0WBNhZrD758CgKXP5D7YFuj1PlmVRZeces9RAAhcGNYnpPh9OfXRefyVn5snnILuu7PnWu3YQ0n987TCyzFcPsDL7ITsofv7iYkzHYnnLYK9hacoORlK+xftlG0DON/7oej23UqouCepDY+eNkyMzuKNELu6tZj9fylWXUTzSeohySGSgTm+Ddys1rOhTVIR75Ndv6FI9IBvRA5RfVWSmb/2IUUNfhM3e96mEA=
